### PR TITLE
fix: add warning to `fetch()` calls that will change the requested port

### LINKED ISSUE #1320: Fetch ignoring port
### 🐛 Bug Report

I'm having an extremely strange issue where Fetch() completely ignores any custom port when actually running in the deployed Worker but from the quick editor, it works as expected.

I've gotten the Worker as simplified as much as possible to try and debug this issue. To explain the test, I have Nginx running on 443 and another application on 4567. 

#### Steps to reproduce
```js
addEventListener('fetch', event => {
  event.respondWith(rewriteURL(event.request))
})
 
async function rewriteURL(request) {
  let urlWithPort = new URL("https://test.file.properties:4567/download/file")
  urlWithPort.port = 9055
  //return new Response(urlWithPort) - shows the port 9055 in the URL, as it should.
  const response = await fetch(urlWithPort, request)
  return response
}
```

#### What did you expect to see?
* When I test this code from the quick editor, I get 502 (expected) because I specified port 9055 and it's using that as I told it to
* When I test this code by visiting the deployed URL, I get an Nginx 404 page (so it's completely ignoring port 9055)
* If you change `urlWithPort.port` to 4567 (or remove it), the quick editor will successfully return it from the application running on port 4567 (expect some JSON error about processing the request because the application expects some headers and parameters)

I'm expecting the deployed Worker to use the custom specified port when doing Fetch() just like it does on the quick editor.

--
Wrangler wasn't used to create this worker, so I didn't specify any environment. I've entirely used the online quick editor.

### PR DESCRIPTION
**Pull request by petebacondarwin**
In Workers published to the Edge (rather than previews) there is a bug where a custom port on a downstream fetch request is ignored, defaulting to the standard port.
For example, `https://my.example.com:668` will actually send the request to `https://my.example.com:443`.

This does not happen when using `wrangler dev` (both in remote and local mode), but to ensure that developers are aware of it this change displays a runtime warning in the console when the bug is hit.

Closes #1320

### CODE REVIEW

File: packages/wrangler/templates/checked-fetch.js [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+    "https:": "443",
+    "http:": "80",
+  };
+  return (request, init) => {
+    const url = new URL(
+      (typeof request === "string" ? new Request(request, init) : request).url
+    );
+    if (PORT_MAPPING[url.protocol] !== url.port) {
+      console.warn(
+        `WARNING: non-standard fetch() behaviour.\nThe port of the URL being fetched "${url.toString()}" will be converted to the "default port" (${
```
Comment (Electroid) [inline packages/wrangler/templates/checked-fetch.js:13]: Should we warn that this is a bug/known issue?

**Comment by petebacondarwin** [comment]
If you are interested in testing this locally, you can try adding the following fetch requests to a Worker and running `wrangler dev`:

```ts
await fetch("http://portquiz.net");
await fetch("https://portquiz.takao-tech.com");
await fetch("http://portquiz.net:8989");
await fetch("https://portquiz.takao-tech.com:8989");
await fetch("http://portquiz.net");
await fetch("https://portquiz.takao-tech.com");
await fetch("http://portquiz.net:8988");
await fetch("https://portquiz.takao-tech.com:8988");
await fetch("http://portquiz.net");
await fetch("https://portquiz.takao-tech.com");
await fetch("http://portquiz.net:8989");
await fetch("https://portquiz.takao-tech.com:8989");
```

**Review by threepointone — APPROVED** [review]
Been looking forward to this one. This is the sort of thing wrangler should be doing, adds real value to using it. Thank you very much!

**Comment by jfsiii** [comment]
I really appreciate this fix, but don't understand how adding a warning fixes #1320. The behavior described in #1320 is still present, right? The user now has a much better understanding of what's going on, but any custom port will still be replaced.

**Comment by threepointone** [comment]
Yeah good point. I reopened the issue, let's close it only once we ship the fix in the runtime.
