### PR TITLE
fix: pages dev process exit when proxied process exits

### LINKED ISSUE #1544: 🐛 BUG: `pages dev` hangs when using proxy command that is not executable
### What version of `Wrangler` are you using?

2.0.23

### What operating system are you using?

Linux

### Describe the Bug

Running `wrangler pages dev -- COMMAND` hangs wrangler if `COMMAND` is not an executable (or doesn't exist, even)
`SIGINT` (`CTRL+C`) does not terminate the process.

Noticed when reporting #1543.

### PR DESCRIPTION
**Pull request by Skye-31**
Currently, if the process pages dev is proxying exists or crashes, pages dev does not clean it up, and attempts to continue proxying requests to it, resulting in it throwing 502 errors. This fixes that behaviour to make wrangler exit with the code the child_process exits with.

Possibly actually fixes #1544

### CODE REVIEW

File: packages/wrangler/src/pages/dev.tsx [hunk 1]
```diff
@@ -402,6 +394,8 @@ async function spawnProxyProcess({
 
 	proxy.on("close", (code) => {
 		logger.error(`Proxy exited with status ${code}.`);
+		CLEANUP();
+		process.exit(code ?? 0);
```
Comment (GregBrimble) [inline packages/wrangler/src/pages/dev.tsx:398]:
```suggestion
		process.exitCode = code ?? 0;
```

Comment (Skye-31) [reply packages/wrangler/src/pages/dev.tsx:398]: I added this logic in just to make it pass the exit code through in case wrangler is being run by something like nodemon or docker, which may otherwise restart it if it exited with a 0, happy to always make it 0 or whatever though

**Review by WalshyDev — APPROVED** [review]
