### PR TITLE
Ignore non-JS files when compiling Pages Functions

### LINKED ISSUE #75: `wrangler pages dev` crashes if `tsconfig.json` exists in `/functions`
Having a `tsconfig.json` file in the `/functions` folder causes `wrangler pages dev` to crash.

Looking at the error output, wrangler is trying to compile `tsconfig.json` with esbuild which fails and then crashes wrangler.

## Environment Information

- Node.js v16.10.0
- NPM v7.24.0
- OS: Ubuntu 20.04.3 (running on Windows 11 via WSL)

## Steps to reproduce

- Create a new Cloudflare Pages compatible project with TS. E.g. Vite with `vue-ts`: `npm init vite@latest foo -- --template vue-ts`
- Install npm packages `cd foo && npm i`
- Create a functions directory and add a test function:

`/functions/api/test.ts`:

```ts
// Uses the example code from https://developers.cloudflare.com/pages/platform/functions#writing-your-first-function

export async function onRequest(context) {
  // Contents of context object
  const {
    request, // same as existing Worker API
    env, // same as existing Worker API
    params, // if filename includes [id] or [[path]]
    waitUntil, // same as ctx.waitUntil in existing Worker API
    next, // used for middleware or to fetch assets
    data, // arbitrary space for passing data between middlewares
  } = context;

  return new Response("Hello, world!");
}
```

- Run with wrangler `npx wrangler pages dev -- npm run dev`. Works ✅
- Add a `tsconfig.json` file in `/functions`.

`/functions/tsconfig.json`:

```json
{
  "compilerOptions": {
    "target": "ES2020",
    "module": "CommonJS",
    "lib": ["ES2020"],
    "types": ["@cloudflare/workers-types"]
  }
}
```

- Run with wrangler `npx wrangler pages dev -- npm run dev`. Fails ❌

Error output: 

```
Running npm run dev...
Sleeping 5 seconds to allow proxy process to start before attempting to automatically determine port...
To skip, specify the proxy port with --proxy.
[proxy]: 
> foo@0.0.0 dev
> vite


[proxy]: Pre-bundling dependencies:
  vue

[proxy]: (this will be run only when your dependencies or config have changed)

[proxy]: 
  vite v2.6.14 dev server running at:


[proxy]:   > Local: http://localhost:3000/
  > Network: use `--host` to expose

  ready in 394ms.


Automatically determined the proxy port to be 3000.
/home/drevan/projects/foo/node_modules/@cloudflare/pages-functions-compiler/node_modules/esbuild/lib/main.js:1493
  let error = new Error(`${text}${summary}`);
              ^

Error: Transform failed with 1 error:
<stdin>:2:19: error: Expected ";" but found ":"
    at failureErrorWithLog (/home/drevan/projects/foo/node_modules/@cloudflare/pages-functions-compiler/node_modules/esbuild/lib/main.js:1493:15)
    at /home/drevan/projects/foo/node_modules/@cloudflare/pages-functions-compiler/node_modules/esbuild/lib/main.js:1282:29
    at /home/drevan/projects/foo/node_modules/@cloudflare/pages-functions-compiler/node_modules/esbuild/lib/main.js:629:9
    at handleIncomingPacket (/home/drevan/projects/foo/node_modules/@cloudflare/pages-functions-compiler/node_modules/esbuild/lib/main.js:726:9)
    at Socket.readFromStdout (/home/drevan/projects/foo/node_modules/@cloudflare/pages-functions-compiler/node_modules/esbuild/lib/main.js:596:7)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:199:23) {
  errors: [
    {
      detail: undefined,
      location: {
        column: 19,
        file: '<stdin>',
        length: 1,
        line: 2,
        lineText: '  "compilerOptions": {',
        namespace: '',
        suggestion: ''
      },
      notes: [],
      pluginName: '',
      text: 'Expected ";" but found ":"'
    }
  ],
  warnings: []
}
/home/drevan/projects/foo/node_modules/wrangler/wrangler-dist/cli.js:27069
            throw ex;
            ^

BuildError [1]: Build failed with exit code 1
    at ChildProcess.<anonymous> (file:///home/drevan/projects/foo/node_modules/@miniflare/core/dist/src/index.js:214:25)
    at ChildProcess.emit (node:events:390:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12) {
  code: 1,
  cause: undefined
}
```

### PR DESCRIPTION
**Pull request by GregBrimble**
Fixes #75

More strictly check file extensions when crawling the `/functions` directory to ensure we're only trying to include JS files.

### CODE REVIEW

File: packages/wrangler/pages/functions/filepath-routing.ts [hunk 1]
```diff
@@ -33,7 +33,7 @@ export async function generateConfigFromFileTree({
 
   await forEachFile(baseDir, async (filepath) => {
     const ext = path.extname(filepath);
-    if (/\.(mjs|js|ts)/.test(ext)) {
+    if (/^\.(mjs|js|ts)$/.test(ext)) {
```
Comment (threepointone) [inline packages/wrangler/pages/functions/filepath-routing.ts:36]:
```suggestion
    if (/^\.(mjs|js|ts|tsx|jsx)$/.test(ext)) {
```

**Review by threepointone — APPROVED** [review]

File: packages/wrangler/pages/functions/filepath-routing.ts [hunk 2]
```diff
@@ -33,7 +33,7 @@ export async function generateConfigFromFileTree({
 
   await forEachFile(baseDir, async (filepath) => {
     const ext = path.extname(filepath);
-    if (/\.(mjs|js|ts)/.test(ext)) {
+    if (/^\.(mjs|js|ts|tsx|jsx)$/.test(ext)) {
       // transform the code to ensure we're working with vanilla JS + ESM
       const { code } = await transform(await fs.readFile(filepath, "utf-8"), {
         loader: ext === ".ts" ? "ts" : "js",
```
Comment (threepointone) [inline packages/wrangler/pages/functions/filepath-routing.ts:39]: oh hmm maybe you should do a check for `.tsx` here too?
