### PR TITLE
Pipe through the DO bindings to get shimmed

### LINKED ISSUE #2335: 🐛 BUG: D1 not working from within a Durable Object
### What version of `Wrangler` are you using?

2.6.0

### What operating system are you using?

Mac 13.0.1

### Describe the Bug

Unable to access D1 from env binding in Durable Object.

If I console log the `env` in my Durable Object constructor I see this

```{ __D1_BETA__db: BetaDatabase { },```

and attempts to use the D1 binding the way I do in the worker do not work.

Is it possible to use D1 from within a Durable Object? Is there some setup I am missing here, or is it just a bug in `wrangler dev` ?

### PR DESCRIPTION
**Pull request by geelen**
**What this PR solves / how to test:**
This PR makes it possible to access D1 bindings from Durable Objects.

To test, make a durable object, add D1 bindings to your project, and try query D1 from it.

**Author has included the following, where applicable:**

- [x] Changeset

**Reviewer has performed the following, where applicable:**

- [x] Checked for inclusion of a relevant changeset
- [x] Manually pulled down the changes and spot-tested

Fixes #2335

### CODE REVIEW

**Comment by petebacondarwin** [comment]
What is the use-case/motivation for this?

**Comment by rozenmd** [comment]
@petebacondarwin https://github.com/cloudflare/wrangler2/issues/2335

**Comment by rozenmd** [comment]
Code is good to review, but this PR is blocked until I can verify it works via a preview release

**Comment by petebacondarwin** [comment]
Do we need a preview release to test? Why not just build locally and test?

File: packages/wrangler/src/bundle.ts [hunk 1]
```diff
@@ -784,9 +792,19 @@ async function applyD1BetaFacade(
...
+	doBindings: DurableObjectBindings
 ): Promise<Entry> {
 	const targetPath = path.join(tmpDirPath, "d1-beta-facade.entry.js");
+	const maskedDoBindings = doBindings
+		// Don't shim anything not local to this worker
+		.filter((b) => !b.script_name)
+		// Reexport the DO classnames
+		.map(
+			(b) =>
+				`export const ${b.class_name} = maskDurableObjectDefinition(OTHER_EXPORTS.${b.class_name})`
```
Comment (petebacondarwin) [inline packages/wrangler/src/bundle.ts:805]: Don't we want a semicolon after every statement, rather than only in-between multiple export statements?

File: packages/wrangler/src/dev/start-server.ts [hunk 2]
```diff
@@ -109,6 +110,7 @@ export async function startDevServer(
 			testScheduled: props.testScheduled,
 			local: props.local,
 			experimentalLocal: props.experimentalLocal,
+			doBindings: props.bindings.durable_objects?.bindings || [],
```
Comment (petebacondarwin) [inline packages/wrangler/src/dev/start-server.ts:113]:
```suggestion
			doBindings: props.bindings.durable_objects?.bindings ?? [],
```

File: packages/wrangler/templates/d1-beta-facade.js [hunk 3]
```diff
@@ -238,4 +238,11 @@ var shim_default = {
...
 	},
 };
-export { shim_default as default };
+var maskDurableObjectDefinition = (cls) =>
+	class extends cls {
+		constructor(state, env) {
+			super(state, getMaskedEnv(env));
+		}
+	};
+__DO_REEXPORTS__;
```
Comment (petebacondarwin) [inline packages/wrangler/templates/d1-beta-facade.js:247]: If there are no durable objects to export this would end up leaving an empty statement here, right?

How about instead, we remove the semicolon here, and ensure that any injected exports always end with a semicolon?

```suggestion
__DO_REEXPORTS__
```

File: packages/wrangler/templates/d1-beta-facade.js [hunk 4]
```diff
@@ -238,4 +238,11 @@ var shim_default = {
...
+export { shim_default as default, maskDurableObjectDefinition };
```
Comment (penalosa) [inline packages/wrangler/templates/d1-beta-facade.js:248]: Does `maskDurableObjectDefinition` need exported?

Comment (rozenmd) [reply packages/wrangler/templates/d1-beta-facade.js:248]: Only way I could stop `esbuild` from blowing away `maskDurableObjectDefinition` when the shim gets built (since it looks like dead code to esbuild)

**Comment by petebacondarwin** [comment]
When I run this locally I cannot see these new exports being added...
Perhaps I am doing something wrong. I am working with the `fixtures/workers-chat-demo` code and doing the following:

- change wrangler.toml to include:
  ```toml  
  [[d1_databases]]
  binding = "xxxx"
  database_name = "xxxx"
  database_id = "xxxx"
  ```
- change chat.mjs to include:
  ```ts
  async fetch(request, env) {
    env.xxxx.prepare();
  ```
- from the root of the repo: `npm run build`
- from `fixtures/workers-chat-demo`: `npx wrangler publish --dry-run --outdir tmp`

What I see output is a file called `d1-beta-facade.entry.js`, which ends with:

```js
var maskDurableObjectDefinition = (cls) => class extends cls {
  constructor(state, env) {
    super(state, getMaskedEnv(env));
  }
};
export {
  ChatRoom,
  RateLimiter,
  shim_default as default,
  maskDurableObjectDefinition
};
```

But not the wrapped DurableObject classes.

File: packages/wrangler/templates/d1-beta-facade.js (hunk 3 above)
Comment (penalosa) [reply packages/wrangler/templates/d1-beta-facade.js:247]: Can the source for CFSQL/d1js be included here rather than a build output file?

**Comment by rozenmd** [comment]
That helps a lot @petebacondarwin - will use that to try fix it

File: packages/wrangler/templates/d1-beta-facade.js (hunk 3 above)
Comment (rozenmd) [reply packages/wrangler/templates/d1-beta-facade.js:247]: Actually no @petebacondarwin - looks like esbuild strips out the stray `;`

File: packages/wrangler/src/bundle.ts [hunk 5]
```diff
@@ -779,17 +789,51 @@ async function applyFirstPartyWorkerDevFacade(
...
 ): Promise<Entry> {
+	let entrypointPath = path.resolve(
+		getBasePath(),
+		"templates/d1-beta-facade.js"
+	);
+	if (doBindings.length > 0) {
+		//we have DO bindings, so we need to shim them
+		const maskedDoBindings = doBindings
+			// Don't shim anything not local to this worker
+			.filter((b) => !b.script_name)
```
Comment (Skye-31) [inline packages/wrangler/src/bundle.ts:805]: Doesn't this mean pages DO bindings won't work with D1 🤔

Comment (rozenmd) [reply packages/wrangler/src/bundle.ts:805]: @GregBrimble @WalshyDev help

Comment (geelen) [reply packages/wrangler/src/bundle.ts:805]: I think it's ok, since a Pages worker can't _define_ a DO, it can only connect to one (unless this has changed?). So when you define & deploy the DO itself, this shim will take effect, then Pages will connect to it and Everything'll Be Fine™.

Comment (Skye-31) [reply packages/wrangler/src/bundle.ts:805]: Ah okay, that's not an issue then!

**Review by rozenmd — APPROVED** [review]

File: .changeset/cuddly-spoons-search.md [hunk 6]
```diff
@@ -0,0 +1,21 @@
+---
+"wrangler": patch
+---
+
+fix: add d1 shim to durable objects
```
Comment (rozenmd) [inline .changeset/cuddly-spoons-search.md:5]:
```suggestion
fix: make it possible to query d1 databases from durable objects
```

**Review by petebacondarwin — COMMENTED** [review]
I know this has landed but I think it would be good to put together a test for this?

I didn't get time to check but I was a bit worried about the "double export" of DO bindings (i.e. the `export * from "worker"` + the explicit `const ${b.class_name} = maskDurableObjectDefinition(OTHER_EXPORTS.${b.class_name})`. What does this end up looking like in the compiled output?

**Comment by rozenmd** [comment]
@petebacondarwin:
```
var ChatRoom2 = maskDurableObjectDefinition(ChatRoom);
var RateLimiter2 = maskDurableObjectDefinition(RateLimiter);
export {
  ChatRoom2 as ChatRoom,
  RateLimiter2 as RateLimiter,
  shim_default as default
};
```

**Comment by petebacondarwin** [comment]
Glad to hear it. I think we could have a test that ran `wrangler publish --outdir tmp --dry-run` to prove this?
