### PR TITLE
Don't immediately exit on Pages Functions compilation error

### LINKED ISSUE #543: 🐛 BUG: wrangler@alpha should SIGTERM react-scripts on error
### What version of `Wrangler` are you using?

0.0.0-046b17d

### What operating system are you using?

Mac

### Describe the Bug

```bash
 ./node_modules/.bin/wrangler  --version
0.0.0-046b17d
```

If the following command exits on error for any reason, react-scripts stays running. 

```bash
./node_modules/.bin/wrangler pages dev -- npx react-scripts start
```

Subsequent runs will produce:

```bash
./node_modules/.bin/wrangler pages dev -- npx react-scripts start
Running npx react-scripts start...
Sleeping 5 seconds to allow proxy process to start before attempting to automatically determine port...
To skip, specify the proxy port with --proxy.
[proxy]: Something is already running on port 3000.

Proxy exited with status 0.
```

### PR DESCRIPTION
**Pull request by GregBrimble**
Fixes #543

Previously, we'd exit the `wrangler pages dev` process if we couldn't immediately compile a Worker from the `functions` directory. We now log the error, but don't exit the process. This means that proxy processes can be cleaned up cleanly on SIGINT and SIGTERM, and it matches the behavior of if a compilation error is introduced once already running (we don't exit then either).

### CODE REVIEW

File: packages/wrangler/src/pages.tsx [hunk 1]
```diff
@@ -805,13 +805,15 @@ export const pages: BuilderCallback<unknown, unknown> = (yargs) => {
...
-          });
+          try {
+            await buildFunctions({
+              scriptPath,
+              functionsDirectory,
+              sourcemap: true,
+              watch: true,
+              onEnd: () => scriptReadyResolve(),
+            });
+          } catch {}
```
Comment (petebacondarwin) [inline packages/wrangler/src/pages.tsx:816]: Perhaps log the error?

Comment (GregBrimble) [reply packages/wrangler/src/pages.tsx:816]: esbuild already does 😊
