### PR TITLE
fix: route deployment fallback for restricted permission API tokens

### LINKED ISSUE #651: 🐛 BUG: Routes do not work if api token is restricted to zone
### What version of `Wrangler` are you using?

0.0.0-21ee93e

### What operating system are you using?

Linux

### Describe the Bug

1. Restrict API token to a zone, for example:
```
Account - Workers R2 Storage:Edit, Workers Tail:Read, Workers KV Storage:Edit, Workers Scripts:Edit, Account Settings:Read
    example.com - Workers Routes:Edit
All users - User Details:Read
```

2. Try to deploy to `routes = ["https://example.com/*"]`
3. Error:
```
 ⛅️ wrangler 0.0.0-21ee93e 
---------------------------
Uploaded test-worker (1.71 sec)

✘ [ERROR] Received a bad response from the API

  Authentication error [code: 10000]
```

Not sure if this is related with the zone inference or a bug on Cloudflare's side

### PR DESCRIPTION
**Pull request by petebacondarwin**
It could be worth reviewing this commit by commit, given that quite a few lines changed.

Fixes #651

### CODE REVIEW

File: packages/wrangler/src/config/config.ts [hunk 1]
```diff
@@ -184,7 +184,7 @@ export interface DevConfig {
   /**
    * Host to forward requests to, defaults to the host of the first route of project
    */
-  host: Config["route"];
+  host: string | undefined;
```
Comment (petebacondarwin) [inline packages/wrangler/src/config/config.ts:187]: I think typing this as `Config["route"]` was a mistake, since in our validation we check that it is a `string`.

File: packages/wrangler/src/create-worker-preview.ts [hunk 2]
```diff
@@ -139,19 +139,18 @@ async function createPreviewToken(
...
+        ? `${
+            worker.name
+            // TODO: this should also probably have the env prefix
+            // but it doesn't appear to work yet, instead giving us the
+            // "There is nothing here yet" screen
+            // ctx.env && !ctx.legacyEnv
+            //   ? `${ctx.env}.${worker.name}`
+            //   : worker.name
+          }.${host.split(".").slice(1).join(".")}`
+        : host,
```
Comment (petebacondarwin) [inline packages/wrangler/src/create-worker-preview.ts:153]: It would be good for the reviewer to look carefully at this change and make sure I didn't break something. I am pretty confident it is correct, but the logic is a bit tricky.

File: packages/wrangler/src/zones.ts [hunk 3]
```diff
@@ -0,0 +1,92 @@
...
+}
+
+/**
+ * Given something that resembles a host, try to infer a zone id from it.
+ *
+ * It's hard to get a 'valid' domain from a string, so we don't even try to validate TLDs, etc.
+ * For each domain-like part of the host (e.g. w.x.y.z) try to get a zone id for it by
+ * lopping off subdomains until we get a hit from the API.
+ */
+export async function getZoneFromHost(host: string): Promise<string> {
```
Comment (threepointone) [inline packages/wrangler/src/zones.ts:76]: Conceptually I've been thinking of a "zone" = {id , host} So let's call the ID string as "zoneId". 
```suggestion
export async function getZoneIdFromHost(host: string): Promise<string> {
```

File: packages/wrangler/src/create-worker-preview.ts [hunk 4]
```diff
@@ -139,19 +139,18 @@ async function createPreviewToken(
...
-          // but it doesn't appear to work yet, instead giving us the
-          // "There is nothing here yet" screen
-          // ctx.env && !ctx.legacyEnv
-          //   ? `${ctx.env}.${worker.name}`
-          //   : worker.name
-        }.${host.split(".").slice(1).join(".")}`
-      : host,
+    host:
+      ctx.host ?? worker.name
+        ? `${
```
Comment (threepointone) [inline packages/wrangler/src/create-worker-preview.ts:144]: this would not use ctx.host if it's available no? as in, if ctx.host and worker.name are both available, then it'll use worker.name, which isn't the desired behaviour I think?

**Review by threepointone — COMMENTED** [review]
Thank you for the work here! I'm certain it works, but I'd love for the implementation o be a tad simpler. I dropped some notes, and I'd be happy to discuss in more detail if you'd like

File: packages/wrangler/src/publish.ts [hunk 5]
```diff
@@ -581,3 +573,159 @@ async function getSubdomain(accountId: string): Promise<string> {
...
+  notProd: boolean
+) {
+  if (notProd) {
+    throw new Error(
+      "Service environments combined with an API token that doesn't have 'All Zones' permissions is not supported.\n" +
+        "Either turn off service environments by setting `legacy_env = true`, creating an API token with 'All Zones' permissions, or logging in via OAuth"
+    );
+  }
+  logger.warn(
+    "The current authentication token does not have 'All Zones' permissions so cannot use the bulk-routes API endpoint.\n" +
```
[the remark this answers is not in the document]
Comment (petebacondarwin) [reply packages/wrangler/src/publish.ts]: Updated the messaging to avoid the use of "bulk-routes API"

File: packages/wrangler/src/zones.ts [hunk 6]
```diff
@@ -0,0 +1,92 @@
...
+}
+
+/**
+ * Try to compute the a zone ID and host name for one or more routes.
+ *
+ * When we're given a route, we do 2 things:
+ * - We try to extract a host from it
+ * - We try to get a zone id from the host
+ */
+export async function* getZonesAndHostsForRoutes(
```
[the remark this answers is not in the document]
Comment (petebacondarwin) [reply packages/wrangler/src/zones.ts]: Aye!

File: packages/wrangler/src/zones.ts (hunk 3 above)
Comment (petebacondarwin) [reply packages/wrangler/src/zones.ts]: Cool. Things are a little complicated because the "host" of a zone is not necessarily the "host" passed through to `wrangler dev`.

File: packages/wrangler/src/publish.ts [hunk 7]
```diff
@@ -581,3 +573,159 @@ async function getSubdomain(accountId: string): Promise<string> {
...
+
+/**
+ * Associate the newly deployed Worker with the given routes.
+ */
+async function publishRoutes(
+  workerUrl: string,
+  routes: Route[],
+  scriptName: string,
+  notProd: boolean
+): Promise<string[]> {
```
[the remark this answers is not in the document]
Comment (petebacondarwin) [reply packages/wrangler/src/publish.ts]: Such a refactoring is a larger effort outside of the scope of this PR.
`workerUrl` is used in a number of places throughout the code of this file.
Let's consider that in a follow up.

I will rearrange these parameters to make it a bit less weird for now.

**Review by threepointone — APPROVED** [review]
Ok this is extremely dope, let's land it and start testing it!
