### PR TITLE
fix: display a warning if the user has a `miniflare` section in their…

### LINKED ISSUE #799: warn if `[miniflare]` is used in wrangler.toml
We currently ignore the `[miniflare]` key in wrangler.toml, but that's actually confusing because folks think we support its configuration values. We should probably throw a warning here. Separately we should implement features similar to the ones miniflare provides (with additional edge equivalents) incl. mounts and testing environment, but that's for 2.1

### PR DESCRIPTION
**Pull request by petebacondarwin**
… `wrangler.toml`.

Closes #799

### CODE REVIEW

File: packages/wrangler/src/config/validation.ts [hunk 1]
```diff
@@ -58,6 +58,14 @@ export function normalizeAndValidateConfig(
     } configuration:`
   );
 
+  deprecated(
+    diagnostics,
+    rawConfig,
+    "miniflare",
+    "Wrangler does not use configuration in the `miniflare` section. Unless you are using the Miniflare binary directly you can remove this section.",
```
Comment (threepointone) [inline packages/wrangler/src/config/validation.ts:65]: This isn't technically a "deprecation" since we never used it, . Also I think we shouldn't use the word "binary".

Comment (petebacondarwin) [reply packages/wrangler/src/config/validation.ts:65]: Yeah - I was at 6s and 7s about calling it a deprecation - but the helper was just so nice to use...
Do you have a suggested alternative to the word "binary"? I wanted to make it clear that you have to be using miniflare directly yourself (outside of Wrangler) rather than knowing that `dev --local` happens to use miniflare internally).

**Review by threepointone — APPROVED** [review]
Better! Let's land this.

File: packages/wrangler/src/config/validation-helpers.ts [hunk 2]
```diff
@@ -14,16 +14,13 @@ export function deprecated<T extends object>(
...
-  const diagonsticMessage = breaking
-    ? `🚨 NO LONGER SUPPORTED: "${fieldPath}":\n${message}`
-    : `🦺 DEPRECATION: "${fieldPath}":\n${message}`;
+  const diagnosticMessage = `${title}: "${fieldPath}":\n${message}`;
   const result = unwindPropertyPath(config, fieldPath);
   if (result !== undefined && result.field in result.container) {
-    (breaking ? diagnostics.errors : diagnostics.warnings).push(
-      diagonsticMessage
-    );
+    diagnostics[`${type}s`].push(diagnosticMessage);
```
Comment (petebacondarwin) [inline packages/wrangler/src/config/validation-helpers.ts:23]: I just want to note how clever TS is now!! It is able to infer that the property names will be either `warnings` or `errors`.

Comment (JacobMGEvans) [reply packages/wrangler/src/config/validation-helpers.ts:23]: Love the use of the new release! Nice refactor 🎸
