### PR TITLE
fix: parsing of node inspector url

### LINKED ISSUE #1226: 🐛 BUG: `wrangler dev --local` occasionally emits 'Waiting for connection...' continuously
### What version of `Wrangler` are you using?

2.0.9

### What operating system are you using?

Windows 10

### Describe the Bug

When I run `wrangler dev --local` in Powershell or cmd, sometimes it'll just emit 'Waiting for connection...' continuously until I force close via Ctrl+C.  Other times it works fine. 

e.g.

```
 ⛅️ wrangler 2.0.8
-------------------
⎔ Starting a local server...
Waiting for connection...
Waiting for connection...
Waiting for connection...
Waiting for connection...
(line above repeats forever)
```

https://github.com/cloudflare/wrangler2/blob/main/packages/wrangler/src/inspect.ts#L290

I've logged the websocket URL being used for the connection in the function above and when the issue occurs it appears the URL is a partial one (e.g. ws://127.0.0.1:9229/91fedb) instead of the full URL returned by `node --inspect` (e.g. ws://127.0.0.1:9229/91fedbcf-52c1-421c-9228-146631a3717b).  Opening a websocket with the partial URL causes the `"unexpected-response"` event to fire (due to the server returning 400 Bad Request) which then results in an endless loop as the connection is retried (see `retryRemoteWebSocketConnection`).

The source of the websocket URL appears to be parsed in:
https://github.com/cloudflare/wrangler2/blob/main/packages/wrangler/src/dev/local.tsx#L255

On my machine this handler typically receives data in two chunks (i.e. the event fires twice).  If a chunk contains a partial URL then the regex matches and `setInspectorUrl` is called with the invalid partial URL (which causes the issue).  If none of the chunks match the regex then `setInspectorUrl` is never called and the issue doesn't occur. 

I've managed to fix this locally by accumulating the chunks and then testing the accumulated data with a modified regex that requires a 36 character UUID in the URL for a match. 

Hope this helps / I'll open a PR with a fix shortly.

### PR DESCRIPTION
**Pull request by timabb031**
Closes #1226 

If there's a more elegant way of solving this issue please let me know / happy to adjust the PR as required.

### CODE REVIEW

File: packages/wrangler/src/dev/local.tsx [hunk 1]
```diff
@@ -251,12 +251,18 @@ function useLocalWorker({
         process.stdout.write(data);
       });
 
+      // parse the node inspector url (which may be received in chunks) from stderr
+      let foundInspectorUrl = false;
+      const stderrData: string[] = [];
```
Comment (petebacondarwin) [inline packages/wrangler/src/dev/local.tsx:256]: How about just

```suggestion
      let stderrData = "";
```

And then append new data to this string?

That would save on having to `join()` it each time.

File: packages/wrangler/src/dev/local.tsx [hunk 2]
```diff
@@ -251,12 +251,18 @@ function useLocalWorker({
...
       local.current.stderr?.on("data", (data: Buffer) => {
+        if (foundInspectorUrl) return;
```
Comment (petebacondarwin) [inline packages/wrangler/src/dev/local.tsx:258]: Currently we don't bother to stop listening when we have found the inspector URL, but this seems like a wise thing to do.

Instead of using a flag for this (and continuing to listen), how about we unbind the event listener once we have got what we want?

**Review by petebacondarwin — CHANGES_REQUESTED** [review]
Thanks for this PR @timabb031 - you are a star!
I made a couple of suggestions. What do you think?

**Comment by timabb031** [comment]
No problem @petebacondarwin! I've updated the PR as per your comments.  Hope that works / let me know if further changes are required.

File: packages/wrangler/src/dev/local.tsx [hunk 3]
```diff
@@ -251,12 +251,16 @@ function useLocalWorker({
...
       });
 
+      // parse the node inspector url (which may be received in chunks) from stderr
+      let stderrData = "";
       local.current.stderr?.on("data", (data: Buffer) => {
+        stderrData += data.toString();
         const matches =
-          /Debugger listening on (ws:\/\/127\.0\.0\.1:\d+\/[A-Za-z0-9-]+)/.exec(
-            data.toString()
+          /Debugger listening on (ws:\/\/127\.0\.0\.1:\d+\/[A-Za-z0-9-]{36})/.exec(
```
Comment (petebacondarwin) [inline packages/wrangler/src/dev/local.tsx:259]: Is the ID always 36 chars long? I understand you are doing this to prevent picking up only some of the ID if it breaks across two chunks, but I wonder if we could be more lenient by looking for a terminating character, such as `\n` or whitespace or something?

**Review by petebacondarwin — COMMENTED** [review]
This looks great! I have one last question before we land this.

File: packages/wrangler/src/dev/local.tsx (hunk 3 above)
Comment (timabb031) [reply packages/wrangler/src/dev/local.tsx]: The ID portion of the URL currently returned by `node --inspect` appears to be a UUID which is always 36 characters long, but I've updated the regex to capture up to `\r` or `\n` as per your suggestion - does that work?

Comment (timabb031) [reply packages/wrangler/src/dev/local.tsx]: Alternatively, the regex could be loosened up further to something like `/Debugger listening on (ws:\/\/.+:\d+\/.+)[\r|\n]/`  which was a slight adaption of https://github.com/nodejs/node/blob/528fef2285b48d66f2ec7b41696da4b596c87c31/test/common/inspector-helper.js#L375

**Review by petebacondarwin — APPROVED** [review]
LGTM thanks.

File: .changeset/brave-ghosts-buy.md [hunk 4]
```diff
@@ -0,0 +1,7 @@
+---
+"wrangler": patch
+---
+
+fix: parsing of node inspector url
+
+This fixes the parsing of the url returned by Node Inspector via stderr which could be received partially in multiple chunks or in a single chunk.
```
Comment (threepointone) [inline .changeset/brave-ghosts-buy.md:7]:
```suggestion
This fixes the parsing of the url returned by Node Inspector via stderr which could be received partially in multiple chunks or in a single chunk.

Closes #1226 
```

File: .changeset/brave-ghosts-buy.md [hunk 5]
```diff
@@ -0,0 +1,9 @@
...
+
+Closes #1226
```
Comment (petebacondarwin) [inline .changeset/brave-ghosts-buy.md:9]: Hmm, for some reason Prettier doesn't like this...

Comment (threepointone) [reply .changeset/brave-ghosts-buy.md]: fixed, trailing whitespace
