### PR TITLE
fix: pages dev handle multiple file extensions

### LINKED ISSUE #870: 🐛 BUG: Pages html handling with multiple extensions - prod vs local difference
### What version of `Wrangler` are you using?

0.0.27

### What operating system are you using?

Windows 10

### Describe the Bug

When you have an HTML file in your output such as `1.18.2.html`, Pages 404s when hitting `/1.18.2` when using `wrangler pages dev`. For example, `https://1f8a4926.mcversions.pages.dev/download/1.18.2` relates to a `/download/1.18.2.html` file.

It appears to work fine in production though as you can see in the URL above.

Full steps to replicate:

- Create `public/1.18.2.html`
- `npx wrangler pages dev ./public`
- `http://localhost:8788/1.18.2` 404s
---
- Deploy to prod
- `https://example.com/1.18.2` works

### PR DESCRIPTION
**Pull request by Skye-31**
Closes #870 

Pages is currently unable to deal with serving files like `/a.b` -> `/a.b.html` in wrangler. This behaviour works in production, however. This PR fixed wrangler not being able to understand those files, and adds tests to deal with it.

### CODE REVIEW

File: packages/wrangler/src/miniflare-cli/assets.ts [hunk 1]
```diff
@@ -466,6 +466,14 @@ async function generateAssetsFetch(
 				return deconstructedResponse;
 			}
 		} else if (hasFileExtension(assetName)) {
+			if ((asset = getAsset(assetName + ".html"))) {
```
Comment (WalshyDev) [inline packages/wrangler/src/miniflare-cli/assets.ts:469]:
```suggestion
			if (asset = getAsset(assetName + ".html")) {
```
redundant brackets

**Review by WalshyDev — APPROVED** [review]
