### PR TITLE
fix: service bindings + wrangler dev ignores pathname when making a request

### LINKED ISSUE #1598: bug: service bindings + wrangler dev ignores pathname when making a request
https://github.com/cloudflare/wrangler2/blob/d4fbd0be5f5801c331a76709cb375a9386117361/packages/wrangler/templates/service-bindings-module-facade.js#L29-L31

We don't construct the full url, so only the root gets called

### PR DESCRIPTION
**Pull request by JacobMGEvans**
Added pathname to the constructed URL.

resolves #1598

### CODE REVIEW

File: packages/wrangler/templates/service-bindings-module-facade.js [hunk 1]
```diff
@@ -28,7 +28,7 @@ export default {
 						}
 						const url = `${details.protocol}://${details.host}${
 							details.port ? `:${details.port}` : ""
-						}`;
+						}${details.pathname ? `${details.pathname}` : ""}`;
```
Comment (GregBrimble) [inline packages/wrangler/templates/service-bindings-module-facade.js:31]: This is still going to be missing any query params.

I'd re-write it to be like:

```
const url = new URL(req.url)
url.protocol = details.protocol
url.host = details.host
if (details.port) url.port = details.port
```

**Review by GregBrimble — CHANGES_REQUESTED** [review]
Left a suggestion

**Review by GregBrimble — APPROVED** [review]
Thanks @JacobMGEvans ! :)
