### PR TITLE
Fallback to `zone_name` on invalid URL error

### LINKED ISSUE #2094: 🐛 BUG: */* route pattern errors with invalid url / could not find zone for *
### What version of `Wrangler` are you using?

2.1.12 & 2.1.13

### What operating system are you using?

Windows

### Describe the Bug

If you use CF for SaaS with a worker as the origin you have to use `*/*` route pattern, however, as of wrangler@2.1.12 support for that pattern was broken. I believe it was due to the following PR: https://github.com/cloudflare/wrangler2/pull/1946/files

Not really sure what the problem was that pr was trying to fix to know how to make a PR to fix both cases 😅

### PR DESCRIPTION
**Pull request by penalosa**
Closes #2094 and #2095

Falls back to `zone_name` when the hostname can't be inferred from a route pattern (essentially only for the wildcard pattern `*/*`

### CODE REVIEW

**Comment by garretcharp** [comment]
Can confirm this does fix #2094 😀

File: packages/wrangler/src/zones.ts [hunk 1]
```diff
@@ -9,12 +9,38 @@ export interface Zone {
...
-		: undefined;
+	if (typeof route === "string") {
+		return getHostFromUrl(route);
+	} else if (typeof route === "object") {
+		try {
+			return getHostFromUrl(route.pattern);
+		} catch (e) {
+			if (
+				(e as { code: string }).code === "ERR_INVALID_URL" &&
+				"zone_name" in route
```
Comment (rozenmd) [inline packages/wrangler/src/zones.ts:37]: Could we update the test to cover this case?

**Comment by JacobMGEvans** [comment]
We need to skip these really flakey tests I know some are related to the dev registry

**Review by JacobMGEvans — APPROVED** [review]
