### PR TITLE
fix: escape function path regex chars

### LINKED ISSUE #1685: 🐛 BUG: `pages dev` router does not escape regex characters correctly.
### What version of `Wrangler` are you using?

2.0.25

### What operating system are you using?

Mac

### Describe the Bug

1. Create a file named `functions/*.ts`.
2. Get a `miniflare` error page showing *Unexpected MODIFIER at 1, expected END*.

### PR DESCRIPTION
**Pull request by Skye-31**
Closes #1685

Currently, if you have a file such as `functions/*.ts`, pages attempts to run path-to-regex on this, and this will fail, as it assumes it's a regex character (it shouldn't be). This results in an `Unexpected MODIFIER at 1, expected END.` error. This PR correctly escapes these characters to solve the issue (confirmed fix from Alastair)

### CODE REVIEW

File: packages/wrangler/templates/pages-template-worker.ts [hunk 1]
```diff
@@ -1,5 +1,8 @@
 import { match } from "path-to-regexp";
 
+//note: this explicitly does not include the * character, as pages requires this
+const escapeRegex = /[.+?^${}()|[\]\\]/g;
```
Comment (jahands) [inline packages/wrangler/templates/pages-template-worker.ts:4]: Since regex is kinda hard to read, it'd be cool if we put a comment here showing some examples of paths that would break, that now work. Eg.
```
// fixes paths like:
// /*foo.ts by converting it to /\*foo.ts
```

**Review by jahands — APPROVED** [review]

File: packages/wrangler/templates/pages-template-worker.ts (hunk 1 above)
Comment (Skye-31) [reply packages/wrangler/templates/pages-template-worker.ts:4]: Good idea!
