### PR TITLE
Abort signalling

### LINKED ISSUE #375: Error when running ctrl-c in dev mode
### What version of `Wrangler` are you using?

0.0.0-b8e3b01 (alpha)

### What operating system are you using?

Mac

### Describe the Bug

The following error occurs when running `ctrl-c` when `wrangler dev` is active. Sometimes the errors appears, but sometimes it does not.

```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    at Remote (/.../node_modules/wrangler/wrangler-dist/cli.js:113212:42)
    at Dev (/.../node_modules/wrangler/wrangler-dist/cli.js:113160:13)
    at ErrorBoundary2 (/.../node_modules/wrangler/wrangler-dist/cli.js:92101:39)
    at withErrorBoundary(Dev)
    at App (/.../node_modules/wrangler/wrangler-dist/cli.js:76011:9)
```

### PR DESCRIPTION
**Pull request by JacobMGEvans**
fix: abort async operations in the `Remote` component to avoid unwanted side-effects
When the `Remote` component is unmounted, we now signal outstanding `fetch()` requests, and
`waitForPortToBeAvailable()` tasks to cancel them. This prevents unexpected requests from appearing
after the component has been unmounted, and also allows the process to exit cleanly without a delay.

fixes #375

### CODE REVIEW

File: packages/wrangler/src/proxy.ts [hunk 1]
```diff
@@ -398,7 +404,7 @@ function createStreamHandler(
  */
 export async function waitForPortToBeAvailable(
   port: number,
-  options: { retryPeriod: number; timeout: number }
+  options: { retryPeriod: number; timeout: number; abortCtrl?: AbortSignal }
```
Comment (threepointone) [inline packages/wrangler/src/proxy.ts:407]:
```suggestion
  options: { retryPeriod: number; timeout: number; abortSignal?: AbortSignal }
```

File: packages/wrangler/src/proxy.ts [hunk 2]
```diff
@@ -289,11 +289,16 @@ export function usePreviewServer({
   // Start/stop the server whenever the
   // containing component is mounted/unmounted.
   useEffect(() => {
+    const abortCtrl = new AbortController();
```
Comment (threepointone) [inline packages/wrangler/src/proxy.ts:292]:
```suggestion
    const abortController = new AbortController();
```

File: packages/wrangler/src/dev/remote.tsx [hunk 3]
```diff
@@ -106,6 +106,7 @@ export function useWorker(props: {
   const startedRef = useRef(false);
 
   useEffect(() => {
+    const abortCtrl = new AbortController();
```
Comment (threepointone) [inline packages/wrangler/src/dev/remote.tsx:109]:
```suggestion
    const abortController = new AbortController();
```

File: packages/wrangler/src/create-worker-preview.ts [hunk 4]
```diff
@@ -57,7 +57,8 @@ export interface CfPreviewToken {
  */
 async function sessionToken(
   account: CfAccount,
-  ctx: CfWorkerContext
+  ctx: CfWorkerContext,
+  abort: AbortSignal
```
Comment (threepointone) [inline packages/wrangler/src/create-worker-preview.ts:61]:
```suggestion
  abortSignal: AbortSignal
```

File: packages/wrangler/src/create-worker-preview.ts [hunk 5]
```diff
@@ -155,10 +158,14 @@ async function createPreviewToken(
 export async function createWorkerPreview(
   init: CfWorkerInit,
   account: CfAccount,
-  ctx: CfWorkerContext
+  ctx: CfWorkerContext,
+  abort: AbortSignal
```
Comment (threepointone) [inline packages/wrangler/src/create-worker-preview.ts:162]:
```suggestion
  abortSignal: AbortSignal
```

File: packages/wrangler/src/create-worker-preview.ts [hunk 6]
```diff
@@ -96,11 +97,13 @@ function randomId(): string {
 async function createPreviewToken(
   account: CfAccount,
   worker: CfWorkerInit,
-  ctx: CfWorkerContext
+  ctx: CfWorkerContext,
+  abort: AbortSignal
```
Comment (threepointone) [inline packages/wrangler/src/create-worker-preview.ts:101]:
```suggestion
  abortSignal: AbortSignal
```

File: packages/wrangler/src/proxy.ts [hunk 7]
```diff
@@ -421,6 +427,9 @@ export async function waitForPortToBeAvailable(
     }
 
     function checkPort() {
+      // Will clear the interval and timeout if signal is called,
+      // using resolve prevents Error messages on the console.
+      options.abortCtrl?.aborted && doResolve();
```
Comment (threepointone) [inline packages/wrangler/src/proxy.ts:432]: let's wrap this in a conditional 
```suggestion
      if(options.abortCtrl?.aborted){
        doResolve();
      }
```

File: .changeset/wet-tables-pretend.md [hunk 8]
```diff
@@ -0,0 +1,9 @@
+---
+"wrangler": patch
+---
+
+fix: abort some of the fetches when we unmount the `Remote` component.
+Adding abort to the `waitForPortToBeAvailable` as an option and in the `useEffect` the abort signal is called in the return which allows for graceful closing with no hanging
+of the `waitForPortToBeAvailable`
```
Comment (petebacondarwin) [inline .changeset/wet-tables-pretend.md:7]:
```suggestion
fix: abort async operations in the `Remote` component to avoid unwanted side-effects

When the `Remote` component is unmounted, we now signal outstanding `fetch()` requests, and
`waitForPortToBeAvailable()` tasks to cancel them. This prevents unexpected requests from appearing
after the component has been unmounted, and also allows the process to exit cleanly without a delay.
```

**Review by petebacondarwin — COMMENTED** [review]
I agree with @threepointone's suggestions; but otherwise LGTM.

**Review by petebacondarwin — CHANGES_REQUESTED** [review]
Actually I wonder if the `waitForPortToBeAvailable()` abort should be more along the lines of:

```ts
export async function waitForPortToBeAvailable(
  port: number,
  options: { retryPeriod: number; timeout: number; abortCtrl?: AbortSignal }
): Promise<void> {
  return new Promise((resolve, reject) => {
    abortSignal.onabort(() => {
      const abortError = new Error("");
      (error as {code: string}).code = "ABORT_ERR";
      reject(abortError);
    });
```

File: packages/wrangler/src/proxy.ts [hunk 9]
```diff
@@ -398,9 +404,15 @@ function createStreamHandler(
  */
 export async function waitForPortToBeAvailable(
   port: number,
-  options: { retryPeriod: number; timeout: number }
+  options: { retryPeriod: number; timeout: number; abortSignal: AbortSignal }
 ): Promise<void> {
   return new Promise((resolve, reject) => {
+    // eslint-disable-next-line @typescript-eslint/no-explicit-any
+    (options.abortSignal as any).addEventListener("abort", () => {
+      const error = new Error("");
```
Comment (threepointone) [inline packages/wrangler/src/proxy.ts:412]: This will log "Failed to start server:" which will be confusing to anyone who reads it. Could we add a code or something this `error`, and read it on line 307 and not log anything if it's an aborted attempt? Like @petebacondarwin described in https://github.com/cloudflare/wrangler2/pull/732#pullrequestreview-927401192

Comment (petebacondarwin) [reply packages/wrangler/src/proxy.ts:414]:
```suggestion
      const abortError = new Error("waitForPortToBeAvailable() aborted");
      (error as {code: string}).code = "ABORT_ERR";
```

**Review by petebacondarwin — CHANGES_REQUESTED** [review]
Just that one change - otherwise LGTM!

**Review by petebacondarwin — APPROVED** [review]
