### PR TITLE
fix: use node http instead of faye-websocket in proxy server

### LINKED ISSUE #1767: 🐛 BUG: `Sec-WebSocket-Protocol` header not returned in WebSocket upgrade responses
### What version of `Wrangler` are you using?

2.0.28

### What operating system are you using?

Mac

### Describe the Bug

When returning a `Response` with a [`Sec-WebSocket-Protocol`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Protocol_upgrade_mechanism#sec-websocket-protocol) header, the protocol is never returned to the client.

### Example

```js
export default {
  async fetch(request) {
    const url = new URL(request.url);
    if (url.pathname === "/") {
      return new Response(
        `<script>
        const webSocket = new WebSocket("ws://localhost:8787/ws", ["protocol1", "protocol2", "protocol3"]);
        webSocket.addEventListener("open", () => {
          console.log(webSocket.protocol);
        });
        </script>`,
        { headers: { "Content-Type": "text/html; charset=utf-8" } }
      );
    } else if (url.pathname === "/ws") {
      const [client, worker] = Object.values(new WebSocketPair());
      worker.accept();
      return new Response(null, {
        status: 101,
        webSocket: client,
        headers: { "Sec-WebSocket-Protocol": "protocol2" },
      });
    } else {
      return new Response(null, { status: 404 });
    }
  },
};
```
Running `wrangler dev`, visiting `http://localhost:8787` in the browser, and opening the JavaScript console shows an empty string. However `protocol2` should be logged.

### PR DESCRIPTION
**Pull request by rozenmd**
Closes #1767 
Closes https://github.com/cloudflare/wrangler2/issues/1812
Closes https://github.com/cloudflare/wrangler2/issues/1813

### CODE REVIEW

File: packages/wrangler/src/proxy.ts [hunk 1]
```diff
@@ -1,14 +1,15 @@
...
+import https from "node:https";
 import { networkInterfaces } from "node:os";
-import WebSocket from "faye-websocket";
 import { createHttpTerminator } from "http-terminator";
 import { useEffect, useRef, useState } from "react";
 import serveStatic from "serve-static";
 import { getHttpsOptions } from "./https-options";
 import { logger } from "./logger";
 import type { CfPreviewToken } from "./create-worker-preview";
+import type WebSocket from "faye-websocket";
```
Comment (rozenmd) [inline packages/wrangler/src/proxy.ts:12]: dumb question, isn't `WebSocket` just a native TypeScript type?

Comment (cameron-robey) [reply packages/wrangler/src/proxy.ts:12]: I don't think WebSocket is a native type - although looks like the `WebSocket` type from `faye-websocket` is actually just any... will go and fix the typing to avoid faye-websocket

Comment (cameron-robey) [reply packages/wrangler/src/proxy.ts]: Have how fixed the typing, and removed the dependence on faye-websocket completely

File: .changeset/tall-radios-report.md [hunk 2]
```diff
@@ -0,0 +1,12 @@
+---
+"wrangler": patch
+---
+
+fix: use node http instead of faye-websocket in proxy server
+
+We change how websockets are handled in the proxy server, fixing multiple issues of websocket behaviour, particularly to do with headers.
+In particular this fixes:
```
Comment (rozenmd) [inline .changeset/tall-radios-report.md:8]:
```suggestion

In particular this fixes:
```

**Comment by cameron-robey** [comment]
We really should make it so that we don't have to rerun tests after updating the changeset...

**Comment by JacobMGEvans** [comment]
> We really should make it so that we don't have to rerun tests after updating the changeset...

Could be doable.

File: packages/wrangler/src/proxy.ts [hunk 3]
```diff
@@ -19,12 +19,7 @@ import type {
 } from "node:http";
 import type { ClientHttp2Session, ServerHttp2Stream } from "node:http2";
 import type { Server as HttpsServer } from "node:https";
-import type ws from "ws";
-
-interface IWebsocket extends ws {
-	// Pipe implements .on("message", ...)
-	pipe<T>(fn: T): IWebsocket;
-}
```
Comment (JacobMGEvans) [inline packages/wrangler/src/proxy.ts:27]: Oh no my workaround 😆

File: packages/wrangler/src/proxy.ts [hunk 4]
```diff
@@ -273,27 +288,47 @@ export function usePreviewServer({
 
 		/** HTTP/1 -> WebSocket (over HTTP/1)  */
 		const handleUpgrade = (
-			message: IncomingMessage,
-			socket: WebSocket,
-			body: Buffer
+			originalMessage: IncomingMessage,
+			originalSocket: Duplex,
+			originalBody: Buffer
```
Comment (mrbbot) [inline packages/wrangler/src/proxy.ts:293]: Nit: https://nodejs.org/api/http.html#event-upgrade
```suggestion
			originalHead: Buffer
```

File: packages/wrangler/src/proxy.ts [hunk 5]
```diff
@@ -273,27 +288,47 @@ export function usePreviewServer({
...
-			cleanupListeners.push(() => {
-				localWebsocket.close();
-				remoteWebsocketClient.close();
-			});
+
+			if (originalBody?.byteLength) originalSocket.unshift(originalBody);
+
+			const runtimeRequest = https.request(
+				{
+					hostname: `${previewToken.host}`,
```
Comment (mrbbot) [inline packages/wrangler/src/proxy.ts:303]: Nit: `previewToken.host` is already a `string`, so there's no need to wrap it in `'s.

**Review by mrbbot — COMMENTED** [review]
Nice! A couple of nits, but 👍. We were going to use a similar WebSocket proxying mechanism in Miniflare 3, and it's possible @penalosa made some additional changes. Worth checking there's nothing we're missing. 🙂

File: packages/wrangler/src/proxy.ts (hunk 5 above)
Comment (JacobMGEvans) [reply packages/wrangler/src/proxy.ts:303]: coerce the string to a string just to make SURE its a string 😆

File: packages/wrangler/src/proxy.ts [hunk 6]
```diff
@@ -273,27 +288,47 @@ export function usePreviewServer({
...
-				{ headers }
-			) as IWebsocket;
-			localWebsocket.pipe(remoteWebsocketClient).pipe(localWebsocket);
-			// We close down websockets whenever we refresh the token.
-			cleanupListeners.push(() => {
-				localWebsocket.close();
-				remoteWebsocketClient.close();
-			});
+
+			if (originalBody?.byteLength) originalSocket.unshift(originalBody);
```
Comment (rozenmd) [inline packages/wrangler/src/proxy.ts:299]:
```suggestion
			if (originalHead?.byteLength) originalSocket.unshift(originalHead);
```

File: packages/wrangler/src/proxy.ts (hunk 5 above)
Comment (cameron-robey) [reply packages/wrangler/src/proxy.ts]: https://github.com/cloudflare/wrangler2/pull/1930/commits/6fe426f058f92c3e89a59f83852fc47a632fe20b

**Review by penalosa — APPROVED** [review]
LGTM
