### PR TITLE
fix: correctly handle entry-point path when publishing 

### LINKED ISSUE #252: wrangler publish fails when ESModule is used
Hello,

I got this error when publishing my ESModule project: `Cannot read properties of undefined (reading '1')`

I reproduce the issue with the following files:

**test.js**
```javascript
import './another.js'

console.log('This is a test')
```

**another.js**
```javascript
console.log('This is another module')
```

**wragnler.toml**
```toml
name = 'test'
type = 'javascript'
account_id = '<ACCOUNT_ID>'
zone_id = '<ZONE_ID>'

compatibility_date = '2021-11-10'

[build.upload]
format = 'modules'
main = './test.js'
```

And then run `npx wrangler@beta publish`

The issue does not exist if `another.js` is not imported. I am not sure this is a bug or it is because v2 is still in beta and ESModule is not yet supported

Thank you.

### PR DESCRIPTION
**Pull request by petebacondarwin**
The `publish` command was failing when the entry-point was specified in the wrangler.toml file and the entry-point imported another file.

This was because we were using the `metafile.inputs` to guess the entry-point file path. But the order in which the source-files were added to this object was not well defined, and so we could end up failing to find a match.

This fix avoids this by using the fact that the `metadata.outputs` object will only contain one element that has the `entrypoint` property - and then using that as the entry-point path. For runtime safety, we now assert that there cannot be zero or multiple such elements.

Fixes #252

### CODE REVIEW

**Comment by threepointone** [comment]
I introduced conflicts to your PR in https://github.com/cloudflare/wrangler2/pull/262 ,sorry!

File: packages/wrangler/src/publish.ts [hunk 1]
```diff
@@ -78,10 +79,12 @@ export default async function publish(props: Props): Promise<void> {
 
   let file: string;
   if (props.script) {
-    file = props.script;
+    // If the script name comes from the command line it is relative to the current working directory.
+    file = path.resolve(props.script);
   } else {
+    // If the script name comes from the config, then it is relative to the wrangler.toml file.
```
Comment (threepointone) [inline packages/wrangler/src/publish.ts:85]: good catch!

**Comment by threepointone** [comment]
We should land this, but I'm deeply concerned with the ambiguity we've introduced. `wrangler dev` can now point to either something hidden inside a `wrangler.toml` file somewhere, or an `index.js` file locally, or (not implemented yet) the `main` field in a parent `package.json`, or (not implemeted yet) the `entry` field in `wrangler.toml`, and there's no way to tell without running the command. We should resolve this before we ship to GA. 

imo, we should deprecate `build.upload.main`, not implement the proposed `entry` field, and not read from `package.json`. We should only have explicit path in CLI.

**Review by threepointone — APPROVED** [review]

File: packages/wrangler/src/publish.ts [hunk 2]
```diff
@@ -1,7 +1,8 @@
 import assert from "node:assert";
 import path from "node:path";
 import { readFile } from "node:fs/promises";
-import esbuild from "esbuild";
+import * as esbuild from "esbuild";
```
Comment (petebacondarwin) [inline packages/wrangler/src/publish.ts:4]: By the way, this change was necessary because (for some reason) the default was not being picked up when being run inside Jest...

File: packages/wrangler/src/publish.ts (hunk 1 above)
Comment (petebacondarwin) [reply packages/wrangler/src/publish.ts:85]: It took me about two hours to get my head around all these different paths. See also the bit below where we have to resolve the entryPoint paths in the `metafile.outputs` relative to `destination.path`!

Comment (threepointone) [reply packages/wrangler/src/publish.ts:85]: madness!
