### PR TITLE
Display a more helpful error when publishing to a route in use by another worker

### LINKED ISSUE #1849: 🐛 BUG: publish fails when attempting to publish a Worker to routes that already exist
### What version of `Wrangler` are you using?

2.1.3

### What operating system are you using?

Mac

### Describe the Bug

When attempting to publish a Worker to a custom domain on routes that already exist on a different worker on the same domain the publish fails with:

✘ [ERROR] A request to the Cloudflare API (/accounts/<account-id>/workers/scripts/<worker-name>/routes) failed.

  workers.api.error.unknown [code: 10013]

I can understand that there may be no one right answer to resolve this issue, but the error message could be improved and could include steps for resolution of common scenarios, e.g: manually remove the routes in the dashboard (or via API I suppose) that are needed for the publish to succeed.

### PR DESCRIPTION
**Pull request by caass**
Display a more helpful error when trying to publish to a route in use by another worker.

Previously, when trying to publish a worker to a route that was in use by another worker,
there would be a really unhelpful message about a failed API call. Now, there's a much
nicer message that tells you what worker is running on that route, and gives you a link
to the workers overview page so you can unassign it if you want.

```text
 ⛅️ wrangler 2.1.11
--------------------
Total Upload: 0.20 KiB / gzip: 0.17 KiB

✘ [ERROR] Can't publish a worker to routes that are assigned to another worker.

  "test-custom-routes-redeploy" is already assigned to route
  test-custom-worker.swag.lgbt

  Unassign other workers from the routes you want to publish to, and then try again.
  Visit
  https://dash.cloudflare.com/<account_id>/workers/overview
  to unassign a worker from a route.
```

Closes #1849

### CODE REVIEW

**Review by JacobMGEvans — APPROVED** [review]

File: packages/wrangler/src/publish/publish.ts [hunk 1]
```diff
@@ -647,6 +648,80 @@ See https://developers.cloudflare.com/workers/platform/compatibility-dates for m
...
+			// so this big array traversal thing is just about
+			// finding workers that have bindings to the routes
+			// you're trying to deploy to.
+			//
+			// the logic is kinda similar (read: duplicated) from publishRoutesFallback,
+			// except here we know we have a good API token or whatever so we don't need
+			// to bother with all the error handling tomfoolery.
+			const routesWithOtherBindings = (
+				await Promise.all(
+					routes.map(async (route) => {
```
Comment (penalosa) [inline packages/wrangler/src/publish/publish.ts:666]: `flatMap`?

File: packages/wrangler/src/publish/publish.ts [hunk 2]
```diff
@@ -647,6 +648,80 @@ See https://developers.cloudflare.com/workers/platform/compatibility-dates for m
...
+							}>(`/zones/${zone.id}/workers/routes`)
+						).filter(
+							({ pattern, script }) =>
+								pattern === routePattern && script !== scriptName
+						);
+					})
+				)
+			)
+				.flat()
+				.reduce((scriptPatternMap, { pattern, script }) => {
```
Comment (penalosa) [inline packages/wrangler/src/publish/publish.ts:688]: Does this need to be a reduce? I feel like a for loop would be clearer (especially with the chain of functions)?

File: packages/wrangler/src/publish/publish.ts [hunk 3]
```diff
@@ -647,6 +648,80 @@ See https://developers.cloudflare.com/workers/platform/compatibility-dates for m
...
+
+					return scriptPatternMap;
+				}, {} as Record<string, string[]>);
+
+			if (Object.keys(routesWithOtherBindings).length > 0) {
+				let errorMessage =
+					"Can't publish a worker to routes that are assigned to another worker.\n";
+
+				for (const worker in routesWithOtherBindings) {
+					const assignedRoutes = routesWithOtherBindings[worker];
```
Comment (penalosa) [inline packages/wrangler/src/publish/publish.ts:703]: `Object.entries()` would let you skip line 703

File: packages/wrangler/src/publish/publish.ts [hunk 4]
```diff
@@ -647,6 +648,80 @@ See https://developers.cloudflare.com/workers/platform/compatibility-dates for m
...
+					if (assignedRoutes.length === 1) {
+						errorMessage += `"${worker}" is already assigned to route ${chalk.underline(
+							assignedRoutes[0]
+						)}\n`;
+					} else {
+						errorMessage += `"${worker}" is already assigned to routes:\n${assignedRoutes.map(
```
Comment (penalosa) [inline packages/wrangler/src/publish/publish.ts:709]: Honestly I feel like using this style even if there's only one route might be nice?

**Review by penalosa — APPROVED** [review]
Couple comments, but looks good!

File: packages/wrangler/src/publish/publish.ts (hunk 2 above)
Comment (rozenmd) [reply packages/wrangler/src/publish/publish.ts:688]: 💯

File: packages/wrangler/src/publish/publish.ts (hunk 1 above)
Comment (caass) [reply packages/wrangler/src/publish/publish.ts:666]: For some reason typescript wasn't thrilled about `flatMap` but I'll give it a shot

File: packages/wrangler/src/publish/publish.ts (hunk 2 above)
Comment (caass) [reply packages/wrangler/src/publish/publish.ts:688]: Sure

File: packages/wrangler/src/publish/publish.ts (hunk 1 above)
Comment (caass) [reply packages/wrangler/src/publish/publish.ts:666]: Oh! It's because the `map` actually returns a promise, not an array

Comment (penalosa) [reply packages/wrangler/src/publish/publish.ts:666]: Is flat going to work then? Will you not need to call .flat on the result of `Promise.all()`?

Comment (penalosa) [reply packages/wrangler/src/publish/publish.ts:666]: Oh lol it already is... sorry!

File: packages/wrangler/src/publish/publish.ts (hunk 3 above)
Comment (caass) [reply packages/wrangler/src/publish/publish.ts:703]: ugh but then prettier breaks the `for` line into three lines...

Comment (penalosa) [reply packages/wrangler/src/publish/publish.ts:691]: Ah okay 😅
