### PR TITLE
fix: warn if the `site.entry-point` configuration is found during publishing

### LINKED ISSUE #282: Deprecate support for `sites['entry-point']` configuration: you don't need that if you're explicitly passing the script.

### PR DESCRIPTION
**Pull request by petebacondarwin**
Is it enough to log a warning? Or should we throw a `new DeprecationError()`?

Fixes #282

### CODE REVIEW

**Comment by threepointone** [comment]
This should probably have a deprecation error, unless we already throw if we don't find an entry point?

**Comment by petebacondarwin** [comment]
Currently we throw if there is neither a command line script nor a configured `build.upload.main` property...

File: packages/wrangler/src/publish.ts [hunk 1]
```diff
@@ -88,6 +88,12 @@ export default async function publish(props: Props): Promise<void> {
     file = path.resolve(path.dirname(__path__), build.upload.main);
   }
 
+  if (config.site?.["entry-point"]) {
```
Comment (threepointone) [inline packages/wrangler/src/publish.ts:91]: could you add this for the dev command as well please?

**Review by threepointone — APPROVED** [review]
one note, but looks good! we can iterate if needed.

**Comment by petebacondarwin** [comment]
I realised that the current flow might be a bit weird for those who have not set up other means for specifying entry-points. They will only receive an error "missing main file". 😢 
I'll update this...

File: packages/wrangler/src/publish.ts (hunk 1 above)
Comment (petebacondarwin) [reply packages/wrangler/src/publish.ts]: Added.

File: packages/wrangler/src/index.tsx [hunk 2]
```diff
@@ -494,6 +494,14 @@ export async function main(argv: string[]): Promise<void> {
         );
       }
 
+      if (config.site?.["entry-point"]) {
+        console.warn(
+          "Deprecation notice: The `site.entry-point` config field is no longer used.\n" +
+            "The entry-point is specified via the command line (see `wrangler dev --help`).\n" +
```
Comment (threepointone) [inline packages/wrangler/src/index.tsx:500]: Feels like a pseudo example would be more helpful here than asking them to see the help text. IMO ofc, your call. 
```suggestion
            "The entry-point should be specified via the command line as `wrangler dev path/to/entry` or the `build.upload.main` config field.\n" +
```

File: packages/wrangler/src/publish.ts [hunk 3]
```diff
@@ -78,13 +78,24 @@ export default async function publish(props: Props): Promise<void> {
     'You need to provide a name when publishing a worker. Either pass it as a cli arg with `--name <name>` or in your config file as `name = "<name>"`'
   );
 
+  if (config.site?.["entry-point"]) {
+    console.warn(
+      "Deprecation notice: The `site.entry-point` config field is no longer used.\n" +
+        "The entry-point should be specified via the command line (see `wrangler publish --help`) or the `build.upload.main` config field.\n" +
```
Comment (threepointone) [inline packages/wrangler/src/publish.ts:84]: same as above, maybe we can use a pseudo path here 
```suggestion
        "The entry-point should be specified via the command line as `wrangler publish path/to/entry` or the `build.upload.main` config field.\n" +
```

File: packages/wrangler/src/publish.ts [hunk 4]
```diff
@@ -78,13 +78,24 @@ export default async function publish(props: Props): Promise<void> {
...
   let file: string;
   if (props.script) {
     // If the script name comes from the command line it is relative to the current working directory.
     file = path.resolve(props.script);
   } else {
     // If the script name comes from the config, then it is relative to the wrangler.toml file.
-    assert(build?.upload?.main, "missing main file");
+    assert(
+      build?.upload?.main,
+      "Missing entry-point: The entry-point should be specified via the command line (see `wrangler publish --help`) or the `build.upload.main` config field."
```
Comment (threepointone) [inline packages/wrangler/src/publish.ts:97]:
```suggestion
      "Missing entry-point: The entry-point should be specified via the command line as `wrangler publish path/to/entry` or the `build.upload.main` config field.\n"
```

**Review by threepointone — APPROVED** [review]
I appreciate the tests here deeply, thank you!

File: packages/wrangler/src/index.tsx (hunk 2 above)
Comment (petebacondarwin) [reply packages/wrangler/src/index.tsx:500]: Yeah - cool. That sounds like a good idea. I'll update

Comment (petebacondarwin) [reply packages/wrangler/src/index.tsx:500]: Actually in the case of `dev` the script must be passed, so it is not possible to use `build.upload.main` here.

File: packages/wrangler/src/publish.ts (hunk 4 above)
Comment (petebacondarwin) [reply packages/wrangler/src/publish.ts:97]: Was the trailing `\n` on purpose here?
