### PR TITLE
Error politely when the user is using an unsupported terminal

### LINKED ISSUE #1992: 🐛 BUG: Wrangler Init fails with: ERROR Raw mode is not supported using the Git for windows terminal
### What version of `Wrangler` are you using?

2.1.10

### What operating system are you using?

Windows

### Describe the Bug

This error occured today when I tried to install wrangler. 

Currently using node v16.17.1
Using [Git for windows terminal](https://gitforwindows.org/) v.2.28.0

Note: Everything works fine in Windows Command prompt

```
$ npx wrangler init failedge-worker
 Ôøà´©Å wrangler 2.1.10
--------------------
Using npm as package manager.
Ô£¿ Created failedge-worker\wrangler.toml
Error: Raw mode is not supported on the current process.stdin, which Ink uses as input stream by default.
Read about how to prevent this error on https://github.com/vadimdemedes/ink/#israwmodesupported
    at App.handleSetRawMode (~\npm\node_modules\wrangler\wrangler-dist\cli.js:71229:21)
    at ~\npm\node_modules\wrangler\wrangler-dist\cli.js:71890:9
    at jh (~\npm\node_modules\wrangler\wrangler-dist\cli.js:20431:26)
    at exports2.unstable_runWithPriority (~\npm\node_modules\wrangler\wrangler-dist\cli.js:16583:16)
    at Pc (~\npm\node_modules\wrangler\wrangler-dist\cli.js:17198:16)
    at Qg (~\npm\node_modules\wrangler\wrangler-dist\cli.js:20383:18)
    at ~\npm\node_modules\wrangler\wrangler-dist\cli.js:20373:13
    at V (~\npm\node_modules\wrangler\wrangler-dist\cli.js:16509:22)
    at Timeout.w [as _onTimeout] (~\npm\node_modules\wrangler\wrangler-dist\cli.js:16350:13)
    at listOnTimeout (node:internal/timers:559:17)

  ERROR Raw mode is not supported on the current process.stdin, which Ink uses
       as input stream by default.
       Read about how to prevent this error on
       https://github.com/vadimdemedes/ink/#israwmodesupported

 - Read about how to prevent this error on
   https://github.com/vadimdemedes/ink/#israwmodesupported
 -App.handleSetRaw ~/AppData/Roaming/npm/node_modules/wrangler/wr
  ode             angler-dist/cli.js:71229:21)
 - ~/AppData/Roaming/npm/node_modules/wrangler/wrangler-dist/cli.
  js:71890:9)
 -jh ~/AppData/Roaming/npm/node_modules/wrangler/wrangler-dist/cl
    i.js:20431:26)
 -exports2.unstable_runWi ~/AppData/Roaming/npm/node_modules/wran
  hPriority              gler/wrangler-dist/cli.js:16583:16)
 -Pc ~/AppData/Roaming/npm/node_modules/wrangler/wrangler-dist/cl
    i.js:17198:16)
 -Qg ~/AppData/Roaming/npm/node_modules/wrangler/wrangler-dist/cl
    i.js:20383:18)
 - ~/AppData/Roaming/npm/node_modules/wrangler/wrangler-dist/cli.
  js:20373:13)
 -V ~/AppData/Roaming/npm/node_modules/wrangler/wrangler-dist/cli
   .js:16509:22)
 -Timeout. ~/AppData/Roaming/npm/node_modules/wrangler/wrangler-d
          ist/cli.js:16350:13)
 - listOnTimeout (node:internal/timers:559:17)
```

### PR DESCRIPTION
**Pull request by caass**
Catch unsupported terminal errors and provide a nicer error message.

Wrangler depends on terminals supporting [raw mode](https://en.wikipedia.org/wiki/Terminal_mode). Previously, attempting to run wrangler from a terminal that didn't support raw mode would result in
an Ink error, which was both an exposure of an internal implementation detail to the user and also not actionable:

```text
  ERROR Raw mode is not supported on the current process.stdin, which Ink uses
       as input stream by default.
       Read about how to prevent this error on
       https://github.com/vadimdemedes/ink/#israwmodesupported
```

Now, we provide a much nicer error, which provides an easy next step for th user:

```text

ERROR: This terminal doesn't support raw mode.

Wrangler uses raw mode to read user input and write output to the terminal, and won't function correctly without it.

Try running your previous command in a terminal that supports raw mode, such as Command Prompt or Powershell.
```

Closes #1992

### CODE REVIEW

**Review by JacobMGEvans — APPROVED** [review]

File: packages/wrangler/src/index.tsx [hunk 1]
```diff
@@ -512,6 +513,32 @@ export async function main(argv: string[]): Promise<void> {
...
+				"Try running your previous command in a terminal that supports raw mode";
+			const oneOfThese =
+				currentPlatform === "win32"
+					? ", such as Command Prompt or Powershell."
+					: currentPlatform === "darwin"
+					? ", such as Terminal.app or iTerm."
+					: "."; // linux user detected, hand holding disengaged.
+
+			logger.error(
+				`${thisTerminalIsUnsupported}\n${soWranglerWontWork}\n${tryRunningItIn}${oneOfThese}`
```
Comment (rozenmd) [inline packages/wrangler/src/index.tsx:540]: :chefskiss:
