### PR TITLE
fix(d1): ensure that migrations support compound statements

### LINKED ISSUE #2463: 🐛 BUG: Incorrect SQL statement splitting
### What version of `Wrangler` are you using?

0.0.0-616f8739

### What operating system are you using?

.

### Describe the Bug

My migrations file:
```sql
[...]

CREATE TRIGGER IF NOT EXISTS update AFTER UPDATE ON t
BEGIN
    DELETE FROM t WHERE ...;
    INSERT INTO t (...)
    VALUES (...);
END;
```

Applying:
```
> wrangler d1 migrations apply DATABASE --local
[...]
🌀 Mapping SQL input into an array of statements
🌀 Loading DB at .wrangler/state/d1/DATABASE.sqlite3
🌀 Mapping SQL input into an array of statements
🌀 Loading DB at .wrangler/state/d1/DATABASE.sqlite3
Migrations to be applied:
┌──────────────────┐
│ Name             │
├──────────────────┤
│ 0000_initial.sql │
└──────────────────┘
About to apply 1 migration(s)
Your database may not be available to serve requests during the migration, continue? (y/n)
🌀 Mapping SQL input into an array of statements
🌀 Loading DB at .wrangler/state/d1/DATABASE.sqlite3

✘ [ERROR] Cannot read properties of undefined (reading 'map')


[...]
```

When logging the `queries` it shows:
```
    'CREATE TRIGGER IF NOT EXISTS update AFTER UPDATE ON t\n' +
      'BEGIN\n    DELETE FROM t WHERE ...',
    'INSERT INTO t (...)\n VALUES (...)",
    'END',
```

The splitting here is incorrect, it didn't respect the `BEGIN .. END` clause, only splited by `;`.

### PR DESCRIPTION
**Pull request by petebacondarwin**
What this PR solves / how to test:

This fix updates the SQL statement splitting so that it does not split in the middle of compound statements.
Previously we were using a third party splitting library, but this needed fixing and was actually unnecessary for our purposes.
So a new splitter has been implemented and the library dependency removed.
Also the error handling in `d1 migrations apply` has been improved to handle a wider range of error types.

Fixes #2463

To test manually, create a simple migration script `migrations/0000_initial.sql` that contains a compound statement:

```
CREATE TABLE IF NOT EXISTS actors (
  id TEXT PRIMARY KEY,
  type TEXT NOT NULL,
  properties TEXT NOT NULL DEFAULT (json_object())
);

CREATE VIRTUAL TABLE IF NOT EXISTS search_fts USING fts5 (
    type,
    name,
);

CREATE TRIGGER IF NOT EXISTS actors_search_fts_update AFTER UPDATE ON actors
BEGIN
    DELETE FROM search_fts WHERE rowid=old.rowid;
    INSERT INTO search_fts (rowid, type, name, preferredUsername)
    VALUES (new.rowid,
            new.type,
            json_extract(new.properties, '$.name'),
            json_extract(new.properties, '$.preferredUsername'));
END;
```

Then update the wrangler to have a pseudo D1 binding:

```
[[d1_databases]]
binding = "DATABASE"
database_name = "database"
database_id = "xxxx-xxxx-xxxx-xxxx"
```

Finally try to apply the migrations locally:

```
npx wrangler d1 migrations apply --local database
```

Associated docs issues/PR:

- N/A

Author has included the following, where applicable:

- [x] Tests
- [x] Changeset

Reviewer has performed the following, where applicable:

- [ ] Checked for inclusion of relevant tests
- [ ] Checked for inclusion of a relevant changeset
- [ ] Checked for creation of associated docs updates
- [ ] Manually pulled down the changes and spot-tested

Fixes # [insert issue number].

### CODE REVIEW

**Review by xtuc — APPROVED** [review]

File: packages/wrangler/src/d1/splitter.ts [hunk 1]
```diff
@@ -0,0 +1,156 @@
...
+		(/[0-9_]/i.test(lastChar) ||
+			lastChar.toLowerCase() !== lastChar.toUpperCase())
+	);
+}
+
+/**
+ * Returns true if the `str` ends with a compound statement `BEGIN` marker.
+ */
+function isCompoundStatementStart(str: string) {
+	return /[\r\s\n]BEGIN[\s\r\n]$/.test(str);
```
Comment (dario-piotrowicz) [inline packages/wrangler/src/d1/splitter.ts:148]: here and below, doesn't `\s` already include `\r` and `\n`?
Screenshot 2023-01-04 at 15 22 51

Comment (petebacondarwin) [reply packages/wrangler/src/d1/splitter.ts:148]: I am never quite sure...

Comment (petebacondarwin) [reply packages/wrangler/src/d1/splitter.ts]: Removed. Thanks.

**Comment by petebacondarwin** [comment]
The new splitter.ts file has 100% code coverage in unit tests 💯

File: packages/wrangler/src/d1/splitter.ts [hunk 2]
```diff
@@ -0,0 +1,161 @@
...
+		(/[0-9_]/i.test(lastChar) ||
+			lastChar.toLowerCase() !== lastChar.toUpperCase())
+	);
+}
+
+/**
+ * Returns true if the `str` ends with a compound statement `BEGIN` marker.
+ */
+function isCompoundStatementStart(str: string) {
+	return /[\s]BEGIN[\s]$/.test(str);
```
Comment (dario-piotrowicz) [inline packages/wrangler/src/d1/splitter.ts:153]: here and below are the square brackets needed?
```suggestion
	return /\sBEGIN\s$/.test(str);
```
also wouldn't you need to add a `+` so that multiple spaces can also be handled?
```suggestion
	return /\s+BEGIN\s+$/.test(str);
```

**Review by geelen — APPROVED** [review]

File: packages/wrangler/src/d1/splitter.ts (hunk 2 above)
Comment (petebacondarwin) [reply packages/wrangler/src/d1/splitter.ts:153]: We only care that there is at least one whitespace either side to prevent a false positive match, e.g. `BEGINNING`.
