### PR TITLE
test: refactor the mock OAuth flow so not to rely upon a real HttpServer

### LINKED ISSUE #755: fix:`publish.test.ts:authentication` tests are making network calls
Noticed that the tests for `authentication` under `publish.test.ts` were taking a long time (8+ seconds!) Running it with wifi off fails the tests, which implies it's making actual network calls. We should fix that by mocking it correctly. 

```
● publish › authentication › drops a user into the login flow if they're unauthenticated

    Failed to send OAuth Grant to wrangler, maybe the server was closed?

      26 |     // don't await this -- it will block the rest of the login flow
      27 |     fetch(`${searchParams.get("redirect_uri")}?${queryParams}`).catch((e) => {
    > 28 |       throw new Error(
         |             ^
      29 |         "Failed to send OAuth Grant to wrangler, maybe the server was closed?",
      30 |         e as Error
      31 |       );

      at src/__tests__/helpers/mock-oauth-flow.ts:28:13

  ● publish › authentication › warns a user when they're authenticated with an API token in wrangler config file

    Failed to send OAuth Grant to wrangler, maybe the server was closed?

      26 |     // don't await this -- it will block the rest of the login flow
      27 |     fetch(`${searchParams.get("redirect_uri")}?${queryParams}`).catch((e) => {
    > 28 |       throw new Error(
         |             ^
      29 |         "Failed to send OAuth Grant to wrangler, maybe the server was closed?",
      30 |         e as Error
      31 |       );

      at src/__tests__/helpers/mock-oauth-flow.ts:28:13
```

Assigning to @caass since she might know what the quick fix is, else we'll all have a look at it.

### PR DESCRIPTION
**Pull request by petebacondarwin**
This should allow tests to run when there is no network connection, and should
also speed up the execution of the tests that rely upon the OAuth flow.

Fixes #755

### CODE REVIEW

File: packages/wrangler/src/__tests__/helpers/mock-http-server.ts [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+            callback?.();
+            return this;
+          },
+        } as unknown as http.Server;
+      });
+  });
+
+  return async (req: Request) => {
+    const resp = new http.ServerResponse(
+      // If you squint you can just about see that an `IncomingMessages` is like a `Request`!
```
Comment (JacobMGEvans) [inline packages/wrangler/src/__tests__/helpers/mock-http-server.ts:29]: 😆

**Review by JacobMGEvans — APPROVED** [review]

**Review by threepointone — APPROVED** [review]
oh thank god, this was driving me up the wall. thank youuuu
