### PR TITLE
fix: Config should be resolved relative to the entrypoint

### LINKED ISSUE #440: Config should be resolved relative to the entrypoint
The resolution of the `wrangler.toml` needs to be tweaked, here's an example I ran into:

* `cd home`
* `wrangler dev project/src/index.js`
* Session starts. Ok, but why are my environment variables empty?
* wrangler searched for a `wrangler.toml` starting from the `home` directory, and found nothing. So it assumed no config.
* Instead, it should have started its search at the entrypoint, and traversed up.

### PR DESCRIPTION
**Pull request by threepointone**
During `dev` and `publish`, we should resolve `wrangler.toml` starting from the entrypoint, and then working up from there. Currently, we start from the directory from which we call `wrangler`, this changes that behaviour to start from the entrypoint instead.

(To implement this, I made one big change: Inside commands, we now have to explicitly read configuration from a path, instead of expecting it to 'arrive' coerced into a configuration object.)

Fixes #440.

### CODE REVIEW

File: packages/wrangler/src/index.tsx [hunk 1]
```diff
@@ -666,8 +674,10 @@ export async function main(argv: string[]): Promise<void> {
         });
     },
     async (args) => {
-      const { filename } = args;
-      const config = args.config as Config;
+      const config = await readConfig(
+        (args.config as ConfigPath) ||
+          (args.script && (await findWranglerToml(path.dirname(args.script))))
```
Comment (petebacondarwin) [inline packages/wrangler/src/index.tsx:679]: Do you need to run `findWranglerToml()` here, since that is exactly what `readConfig()` will do with the path.

File: packages/wrangler/src/index.tsx [hunk 2]
```diff
@@ -57,11 +57,19 @@ const knownBindings = [
...
+  return configPath;
+}
+
 async function readConfig(configPath?: string): Promise<Config> {
   const config: Config = {};
   if (!configPath) {
-    configPath = await findUp("wrangler.toml");
-    // TODO - terminate this early instead of going all the way to the root
+    configPath = await findWranglerToml(process.cwd());
   }
```
Comment (petebacondarwin) [inline packages/wrangler/src/index.tsx:73]: How about always running `findWranglerToml()` from the path given, and make is so that it exits as soon as the path is actually a `wrangler.toml` file?

File: packages/wrangler/src/index.tsx (hunk 1 above)
Comment (threepointone) [reply packages/wrangler/src/index.tsx:679]: Hmm? It won't get the script passed to it, readConfig uses `process.cwd()` (which I can actually remove, since it's the default.)

File: packages/wrangler/src/index.tsx (hunk 2 above)
Comment (threepointone) [reply packages/wrangler/src/index.tsx:73]: Sorry I must not be understanding. `findWranglerToml` does stop looking once it finds a wrangler.toml.

Comment (petebacondarwin) [reply packages/wrangler/src/index.tsx:73]: Sorry I am being confusing. Let me put together what I mean...

**Comment by petebacondarwin** [comment]
OK, so this is what I am getting at. How about we write the beginning of the `readConfig()` to be like:

```ts
async function readConfig(
  configPath: string | undefined = "wrangler.toml",
  cwd = process.cwd()
): Promise<Config> {
  // TODO - terminate this early instead of going all the way to the root
  configPath = await findUp(configPath, { cwd });

  const config: Config = configPath
    ? TOML.parse(await readFile(configPath, "utf-8"))
    : {};

  ...
}
```

Then for most of the commands we can just run:

```ts
const config = await readConfig(args.config);
```

And for `dev` and `publish` we would use:

```ts
const config = await readConfig(args.config, args.script && path.dirname(args.script));
```

**Comment by threepointone** [comment]
Could you explain why you think this is better? In your version, the signature is a bit confusing, because it implies the second arg is necessary even if configPath is truthy. I might be missing some context.

**Review by petebacondarwin — APPROVED** [review]
> Could you explain why you think this is better? In your version, the signature is a bit confusing, because it implies the second arg is necessary even if configPath is truthy. I might be missing some context.

OK, so thinking about this some more. I am happy to drop my idea above. It does make the signature a bit weird.

Happy to go with what you have here. We could probably knock around a number of different approaches but they all have their limitations and this looks pretty robust.
