### PR TITLE
fix: let folks know the URL we're opening during login

### LINKED ISSUE #1259: Wrangler no longer prints login url, force opens browser

### PR DESCRIPTION
**Pull request by rozenmd**
Had to pull a bunch of helper functions out of `user.tsx` to make it possible to mock the generated state value, and codeChallenge value

Closes #1259

### CODE REVIEW

**Comment by threepointone** [comment]
We can make this message simpler by not including the url here then https://github.com/cloudflare/wrangler2/blob/d8ee04f343303e50c976b676cd06075a971081f2/packages/wrangler/src/open-in-browser.ts#L13

File: packages/wrangler/src/user.tsx [hunk 1]
```diff
@@ -1013,6 +1013,7 @@ export async function login(props?: LoginProps): Promise<boolean> {
     server.listen(8976);
   });
 
+  logger.log(`Opened a link in your default browser: ${urlToOpen}`);
```
Comment (petebacondarwin) [inline packages/wrangler/src/user.tsx:1016]:
```suggestion
  logger.log(`Opening a link in your default browser: ${urlToOpen}`);
```

**Review by petebacondarwin — COMMENTED** [review]
Are you missing a change in jest.setup.ts

**Review by threepointone — APPROVED** [review]
