### PR TITLE
fix: Throw error if both `directory` and `command` are specified for `pages dev`

### LINKED ISSUE #1543: 🐛 BUG: `pages dev` silently ignores proxy command if `directory` is specified
### What version of `Wrangler` are you using?

2.0.23

### What operating system are you using?

Linux

### Describe the Bug

Running `wrangler pages dev public -- COMMAND` results in:
```
🚧 'wrangler pages <command>' is a beta command. Please report any issues to https://github.com/cloudflare/wrangler2/issues/new/choose
Compiling worker to "/tmp/functionsWorker-0.9299170373697463.js"...
Compiled Worker successfully.
Retrieving cached values for userId from node_modules/.cache/wrangler
╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ [b] open a browser, [d] open Devtools, [c] clear console, [x] to exit                                                                                                 │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Starting inspector on localhost:9229 failed: address already in use
[pages:wrn] Service bindings are experimental. There may be breaking changes in the future.
[pages:inf] Worker reloaded! (18.47KiB)
[pages:inf] Listening on localhost:8788
[pages:inf] - http://localhost:8788
[pages:inf] Updated `Request.cf` object cache!
```
There is no indication of why COMMAND is being ignored and the only hint that it is ignored at all is that the output is missing `Running COMMAND...`.

The reason is that since `public` was specified as the directory for static files, this `if` is not taken:
https://github.com/cloudflare/wrangler2/blob/bb6e0f7bc0482dcb3122797de8918abd72cde5f3/packages/wrangler/src/pages/dev.tsx#L142-L143
There are no checks for `directory` and `command` both being specified. And this behavior is not mentioned in `--help` either.

### PR DESCRIPTION
**Pull request by Martin-Eriksson**
If both `directory` and `command` are specified for `wrangler
pages dev`, throw an error.

The previous behavior was to silently ignore the `command` argument.

Closes #1543.

### CODE REVIEW

File: packages/wrangler/src/pages/dev.tsx [hunk 1]
```diff
@@ -139,7 +139,12 @@ export const Handler = async ({
 
 	let proxyPort: number | undefined;
 
-	if (directory === undefined) {
+	if (directory !== undefined && command.length) {
```
Comment (WalshyDev) [inline packages/wrangler/src/pages/dev.tsx:142]: Clear code is good
```suggestion
	if (directory !== undefined && command.length > 0) {
```

**Review by WalshyDev — APPROVED** [review]
LGTM, thank you very much!
