### PR TITLE
check for an implementation of AsyncLocalStorage

### LINKED ISSUE #863: Miniflare (local mode) doesn't work in StackBlitz (and possibly other platforms)
Miniflare by default only enables [certain functionality](https://miniflare.dev/core/standards#global-functionality-limits) during the request scope to match the behavior of the workers runtime. The checks that enforce these limits rely on [AsyncLocalStorage](https://nodejs.org/api/async_hooks.html#class-asynclocalstorage), which is not available in all contexts -- they may be missing this class, or their implementation stubs it out.

We can detect if `AsyncLocalStorage` exists and is implemented, and if it's not, we should run miniflare with the flags listed in its documentation:
```js
const mf = new Miniflare({
  globalAsyncIO: true,
  globalTimers: true,
  globalRandom: true,
});
```

While these disable miniflare's checks, it enables local mode to work.

### PR DESCRIPTION
**Pull request by caass**
Certain runtime APIs are only available to workers during the "request context", which is any code that returns after receiving a request and before returning a response.

Miniflare emulates this behavior by using an [`AsyncLocalStorage`](https://nodejs.org/api/async_context.html#class-asynclocalstorage) and [checking at runtime](https://github.com/cloudflare/miniflare/blob/master/packages/shared/src/context.ts#L21-L36) to see if you're using those APIs during the request context.

In certain environments `AsyncLocalStorage` is unavailable, such as in a [webcontainer](https://github.com/stackblitz/webcontainer-core). This function figures out if we're able to run those "request context" checks and returns [a set of options](https://miniflare.dev/core/standards#global-functionality-limits) that indicate to miniflare whether to run the checks or not.

Closes #863

### CODE REVIEW

File: packages/wrangler/src/miniflare-cli/index.ts [hunk 1]
```diff
@@ -2,6 +2,53 @@ import { Log, LogLevel, Miniflare } from "miniflare";
...
+const requestContextCheckOptions = async (): Promise<
+  Pick<MiniflareOptions, "globalAsyncIO" | "globalTimers" | "globalRandom">
+> => {
+  // check that there's an implementation of AsyncLocalStorage
+  let hasAsyncLocalStorage = true;
+  try {
+    const { AsyncLocalStorage } = await import("node:async_hooks");
+    const storage = new AsyncLocalStorage();
+    storage.run(undefined, () => {
+      storage.getStore();
```
Comment (mrbbot) [inline packages/wrangler/src/miniflare-cli/index.ts:31]: It sounds like Web Containers might be stubbing `getStore()` to always return `undefined`. In that case, this code wouldn't throw, but Miniflare would still break without the below options set. Might be worth `run`ning with an actual defined value, and checking it's returned from `getStore()`?

Comment (caass) [reply packages/wrangler/src/miniflare-cli/index.ts:31]: ah ok totally, makes sense

**Comment by caass** [comment]
I didn't write any tests for this since the functionality is behind `wrangler dev`, which we don't have -- I did however ask @eidam if to try out a version with this fix implemented and it seems to work for his projects.

**Comment by eidam** [comment]
Workers project 
https://stackblitz.com/edit/node-gpc6rx?file=package.json

Pages project 
https://stackblitz.com/edit/github-w5ovsh?file=package.json

**Review by JacobMGEvans — COMMENTED** [review]
This looks great to me!! Another big step in Wrangler support in atypical environments.
🥳🥳🥳

**Review by JacobMGEvans — APPROVED** [review]

**Comment by d3lm** [comment]
@caass We are working on git or url dependencies so hopefully that will work soonish.
